---
- name: Setup Python as Python 3
  file: 
    src: python3.7
    dest: /usr/bin/python3 
    state: link
    owner: root
    group: root
  become: yes

- name: Install VSCode
  apt:
    name: code
    state: latest
  become: yes