---
- name: Git checkout for WiringPi
  ansible.builtin.git:
    repo: 'https://github.com/WiringPi/WiringPi.git'
    dest: ~/WiringPi

- name: Build Wiring Pi
  ansible.builtin.shell: ./build
  args:
    chdir: ~/WiringPi

- name: Git Checkout Tutorial
  ansible.builtin.git:
    repo: 'https://github.com/freenove/Freenove_Ultimate_Starter_Kit_for_Raspberry_Pi'
    depth: 1
    dest: ~/Development/Freenove_Kit
